### ISSUE TITLE
Navabar on mobile

### ISSUE THREAD

**Issue by Zelig880** [smartcontractkit/blockchain-developer-hub#295]
Test and fix navbar on mobile

NOTE: the branch needs to be merged into a new branch called "redesign" otherwise it will break the live site!

AC:
- [x] Change the colour of the "hamburger icon" and the "x" icon when using mobile
- [x] Make sure the navbar works correctly on the homepage
- [x] Make sure the navbar works correctly on blog layout (more precisely that the sticky part of it is NOT applied on mobile)
- [x] Maker sure the navbar works correctly on the default layout

**Comment by hdJerry** [comment]
#275 closes this as the major changes which had to do with menu and close icon was changed here as requested then.

**Comment by hdJerry** [comment]
I believe this issue can be closed!
